select * from customers.customer_shopping_behavior;
# Few things or questions that we want to find from the data
# Q1. What is the total revenue generated by male vs. female customers?
select sum(purchase_amount) as total_revenue,gender from
customers.customer_shopping_behavior
group by gender;
------------------------------------------------------------------------------------------------------------------------------------------------------------------
# --Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customers.customer_shopping_behavior 
where discount_applied = 'Yes' and 
purchase_amount >= (select avg(purchase_amount) from customers.customer_shopping_behavior);
------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as avg_rating
from customers.customer_shopping_behavior customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;
------------------------------------------------------------------------------------------------------------------------------------------------------------------
# --Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,avg(purchase_amount)  as avg_amount
from customers.customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;
------------------------------------------------------------------------------------------------------------------------------------------------------------------
# q5   Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select count(customer_id) as total_customers,avg(purchase_amount) as avg_spending, sum(purchase_amount) as total_spending 
from customers.customer_shopping_behavior
where subscription_status in ('Yes','No')
group by subscription_status
order by total_spending,avg_spending desc
;
------------------------------------------------------------------------------------------------------------------------------------------------------------------
# q6 -Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_per
 from customers.customer_shopping_behavior
group  by item_purchased
order by discount_per desc
limit 5;
-------------------------------------------------------------------------------------------------------------------------------
# Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select customer_id,
previous_purchases,
case 
when previous_purchases =1 then 'New' 
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from  customers.customer_shopping_behavior;
----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Q8. What are the top 3 most purchased products within each category?
with item_count as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers.customer_shopping_behavior
group by category,item_purchased
)
select item_rank,category,item_purchased ,total_orders
from item_count
where item_rank <=3;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
#--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeat_buyers,subscription_status
from customers.customer_shopping_behavior
where previous_purchases >5
group by subscription_status;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
# -Q10. What is the revenue contribution of each age group? 
select sum(purchase_amount) as revenue_contribution, age_group
from customers.customer_shopping_behavior
group by age_group
order by revenue_contribution desc;






